In [26]:
#dataset from Kaggle - https://www.kaggle.com/maxhorowitz/nflplaybyplay2009to2016

#import libraries used
import pandas as pd
import numpy as np

#read in data
nfl_data = pd.read_csv(r'D://Python//Data//NFL_pbp_0917_v4.csv')

D:\Python\Anaconda\lib\site-packages\IPython\core\interactiveshell.py:3165: DtypeWarning: Columns (25,51) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [27]:
#look at data- check for NAN and other issues
nfl_data.sample(5)

,Date,GameID,Drive,qtr,down,time,TimeUnder,TimeSecs,PlayTimeDiff,SideofField,...,yacEPA,Home_WP_pre,Away_WP_pre,Home_WP_post,Away_WP_post,Win_Prob,WPA,airWPA,yacWPA,Season
282154,2015-10-11,2015101101,1,1,3.0,11:19,12,3379.0,5.0,CHI,...,0.133624,0.479098,0.520902,0.522516,0.477484,0.520902,-0.043418,-0.048200,0.004782,2015
97517,2011-09-25,2011092514,10,2,1.0,01:46,2,1906.0,0.0,PIT,...,-5.567157,0.242004,0.757996,0.390001,0.609999,0.757996,-0.147997,0.037042,-0.185038,2011
267954,2014-12-28,2014122801,21,4,2.0,07:22,8,442.0,0.0,CLE,...,-3.631941,0.688546,0.311454,0.717226,0.282774,0.311454,-0.028680,0.130016,-0.158696,2014
48902,2010-09-19,2010091903,25,4,1.0,03:41,4,221.0,9.0,CLE,...,NaN,0.423894,0.576106,0.417294,0.582706,0.423894,-0.006601,NaN,NaN,2010
105684,2011-10-23,2011102302,17,4,2.0,10:44,11,644.0,47.0,TEN,...,NaN,0.003087,0.996913,0.004423,0.995577,0.996913,-0.001336,NaN,NaN,2011

In [28]:
#want to know how many missng data points per col
missing_values_count = nfl_data.isnull().sum()

#check the missing values for the first 10 cols
missing_values_count[:10]

Date                0
GameID              0
Drive               0
qtr                 0
down            61154
time              224
TimeUnder           0
TimeSecs          224
PlayTimeDiff      444
SideofField       528
dtype: int64

In [29]:
#what's that as a % of all data
total_cells = np.product(nfl_data.shape)
total_missing = missing_values_count.sum()

(total_missing / total_cells) *100

24.87214126835169

In [30]:
#drop nas - based on cols with min 1 missing value
columns_with_na_drop = nfl_data.dropna(axis=1)
columns_with_na_drop.head()

,Date,GameID,Drive,qtr,TimeUnder,ydstogo,ydsnet,PlayAttempted,Yards.Gained,sp,...,Timeout_Indicator,Timeout_Team,posteam_timeouts_pre,HomeTimeouts_Remaining_Pre,AwayTimeouts_Remaining_Pre,HomeTimeouts_Remaining_Post,AwayTimeouts_Remaining_Post,ExPoint_Prob,TwoPoint_Prob,Season
0,2009-09-10,2009091000,1,1,15,0,0,1,39,0,...,0,None,3,3,3,3,3,0.0,0.0,2009
1,2009-09-10,2009091000,1,1,15,10,5,1,5,0,...,0,None,3,3,3,3,3,0.0,0.0,2009
2,2009-09-10,2009091000,1,1,15,5,2,1,-3,0,...,0,None,3,3,3,3,3,0.0,0.0,2009
3,2009-09-10,2009091000,1,1,14,8,2,1,0,0,...,0,None,3,3,3,3,3,0.0,0.0,2009
4,2009-09-10,2009091000,1,1,14,8,2,1,0,0,...,0,None,3,3,3,3,3,0.0,0.0,2009

In [31]:
#how many columns did we lose?
print("Columns in original dataset: %d \n" % nfl_data.shape[1])
print("Columns with na's dropped: %d" % columns_with_na_drop.shape[1])

Columns in original dataset: 102

Columns with na's dropped: 41

In [33]:
#fill all missing data with 0 as seperate df

filled_nfl_data = nfl_data.fillna(0)
filled_nfl_data.head(20)

,Date,GameID,Drive,qtr,down,time,TimeUnder,TimeSecs,PlayTimeDiff,SideofField,...,yacEPA,Home_WP_pre,Away_WP_pre,Home_WP_post,Away_WP_post,Win_Prob,WPA,airWPA,yacWPA,Season
0,2009-09-10,2009091000,1,1,0.0,15:00,15,3600.0,0.0,TEN,...,0.000000,0.485675,0.514325,0.546433,0.453567,0.485675,0.060758,0.000000,0.000000,2009
1,2009-09-10,2009091000,1,1,1.0,14:53,15,3593.0,7.0,PIT,...,1.146076,0.546433,0.453567,0.551088,0.448912,0.546433,0.004655,-0.032244,0.036899,2009
2,2009-09-10,2009091000,1,1,2.0,14:16,15,3556.0,37.0,PIT,...,0.000000,0.551088,0.448912,0.510793,0.489207,0.551088,-0.040295,0.000000,0.000000,2009
3,2009-09-10,2009091000,1,1,3.0,13:35,14,3515.0,41.0,PIT,...,-5.031425,0.510793,0.489207,0.461217,0.538783,0.510793,-0.049576,0.106663,-0.156239,2009
4,2009-09-10,2009091000,1,1,4.0,13:27,14,3507.0,8.0,PIT,...,0.000000,0.461217,0.538783,0.558929,0.441071,0.461217,0.097712,0.000000,0.000000,2009
5,2009-09-10,2009091000,2,1,1.0,13:16,14,3496.0,11.0,TEN,...,0.000000,0.558929,0.441071,0.578453,0.421547,0.441071,-0.019524,0.000000,0.000000,2009
6,2009-09-10,2009091000,2,1,2.0,12:40,13,3460.0,36.0,TEN,...,0.163935,0.578453,0.421547,0.582881,0.417119,0.421547,-0.004427,-0.010456,0.006029,2009
7,2009-09-10,2009091000,2,1,3.0,12:11,13,3431.0,29.0,TEN,...,0.000000,0.582881,0.417119,0.617544,0.382456,0.417119,-0.034663,0.000000,0.000000,2009
8,2009-09-10,2009091000,2,1,4.0,11:34,12,3394.0,37.0,TEN,...,0.000000,0.617544,0.382456,0.591489,0.408511,0.382456,0.026054,0.000000,0.000000,2009
9,2009-09-10,2009091000,3,1,1.0,11:24,12,3384.0,10.0,TEN,...,0.541602,0.591489,0.408511,0.585405,0.414595,0.591489,-0.006084,-0.024526,0.018442,2009
10,2009-09-10,2009091000,3,1,2.0,10:48,11,3348.0,36.0,TEN,...,1.807459,0.585405,0.414595,0.615159,0.384841,0.585405,0.029754,-0.030157,0.059911,2009
11,2009-09-10,2009091000,3,1,1.0,10:21,11,3321.0,27.0,TEN,...,0.000000,0.615159,0.384841,0.597822,0.402178,0.615159,-0.017337,0.000000,0.000000,2009
12,2009-09-10,2009091000,3,1,2.0,09:43,10,3283.0,38.0,TEN,...,1.229360,0.597822,0.402178,0.607521,0.392479,0.597822,0.009699,-0.031783,0.041482,2009
13,2009-09-10,2009091000,3,1,3.0,09:01,10,3241.0,42.0,TEN,...,0.000000,0.607521,0.392479,0.514075,0.485925,0.607521,-0.093445,0.000000,0.000000,2009
14,2009-09-10,2009091000,3,1,4.0,08:25,9,3205.0,36.0,TEN,...,0.000000,0.514075,0.485925,0.521073,0.478927,0.514075,0.006997,0.000000,0.000000,2009
15,2009-09-10,2009091000,4,1,1.0,08:20,9,3200.0,5.0,TEN,...,0.000000,0.521073,0.478927,0.399273,0.600727,0.478927,0.121800,0.000000,0.000000,2009
16,2009-09-10,2009091000,4,1,1.0,07:57,8,3177.0,23.0,PIT,...,0.137531,0.399273,0.600727,0.368797,0.631203,0.600727,0.030476,0.024894,0.005582,2009
17,2009-09-10,2009091000,4,1,1.0,07:24,8,3144.0,33.0,PIT,...,0.000000,0.368797,0.631203,0.376194,0.623806,0.631203,-0.007397,0.000000,0.000000,2009
18,2009-09-10,2009091000,4,1,2.0,06:57,7,3117.0,27.0,PIT,...,-0.273617,0.376194,0.623806,0.400657,0.599343,0.623806,-0.024463,-0.015287,-0.009176,2009
19,2009-09-10,2009091000,4,1,3.0,06:52,7,3112.0,5.0,PIT,...,0.037212,0.400657,0.599343,0.430491,0.569509,0.599343,-0.029834,-0.030982,0.001148,2009